services:
  - type: web
    name: bizzbuzz-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_USER
        value: YOUR_DB_USER
      - key: DB_PASSWORD
        value: YOUR_DB_PASSWORD
      - key: DB_NAME
        value: BIZZBUZZ
      - key: EMAIL_USER
        value: YOUR_GMAIL
      - key: EMAIL_PASS
        value: YOUR_GMAIL_APP_PASSWORD
      - key: FRONTEND_URL
        value: https://YOUR_GITHUB_USERNAME.github.io
